### ISSUE TITLE
Using code without reference

### ISSUE THREAD

**Issue by pdincau** [softwarejoint/fcm-erlang#1]
Hello,

it seems that you cloned my project [gcm-erlang](https://github.com/pdincau) and pushed it to your repository without forking or making any reference to the original project.

**Comment by pankajsoni19** [comment]
Added reference to your repository and a personal note to you. Thank you for the initial code base.

Let me know if you would like me to add anything else to ReadMe file.

**Comment by pankajsoni19** [comment]
Closing issue as no further comments.
