### ISSUE TITLE
Missing rebar.config

### ISSUE THREAD

**Issue by cystbear** [softwarejoint/fcm-erlang#2]
Hello guys,

could you please add `rebar.config` to your app

**Comment by pankajsoni19** [comment]
It uses erlang.mk build system. No need for that file just hit make.

**Comment by cystbear** [comment]
as you wish.
Just for your information rebar3 located in top "scope" (in Erlang scope), I mean this  https://github.com/erlang/rebar3
in other hand Erlang.mk just @essen's stuff

**Comment by essen** [comment]
You can add the following line to the Makefile to generate a rebar.config automatically:

```
app:: rebar.config
```

It'll get generated every time the project builds, so just commit it after that.

**Comment by cystbear** [comment]
@essen thanks for hint, good to know!

**Comment by pankajsoni19** [comment]
just did that, thx @essen

**Comment by cystbear** [comment]
Glorious commit https://github.com/softwarejoint/fcm-erlang/commit/02edb5489aec71519ddb4ad1263d2e1d36c49630
