### ISSUE TITLE
couple of practical questions

### ISSUE THREAD

**Issue by ahron1** [softwarejoint/fcm-erlang#5]
Nice library, very useful.

Simple questions about the usage (I am using it as a dependency in a Cowboy webserver) - 

1. after starting a pool, is it okay to leave it running indefinitely in the server and keep reusing the same pool for every new notification?

2. in practice, while sending a notification, is it a good idea to first check if the named pool already exists, and if not create it? What is the best way to check this - error/exception handling on the return value of `fcm:push` and `fcm:start_pool_with_json_service_file`? Or is there another way?

3. probably not so relevant right now, but more for my curiosity - are there practical limits on the usage of individual pools? i.e. are there any guidelines about when to create/use new pools?

**Comment by pankajsoni19** [comment]
1. yes. as long as needed.
2. better to start the pool when your application loads. you can do by defining start config in your `sys.config`

there are 2 methods to connect to firebase. using api-key or using json auth file. using json auth file is recommended by google. api-key is deprecated.

yes, check error value response on each push result.

3. create new pool when your application loads in `application:start`.
no such limit. if you are throttled by your cpu /open ports capacity use this on multiple servers in a distributed setup.
